spring:
  shardingsphere:
    datasource:
      names: master,slave1,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/mall?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&&rewriteBatchedStatements=true
        username: root
        password: password
      slave1:
        type: ${spring.shardingsphere.datasource.master.type}
        driver-class-name: ${spring.shardingsphere.datasource.master.driver-class-name}
        url: jdbc:mysql://localhost:3306/mall_slave1?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&&rewriteBatchedStatements=true
        username: ${spring.shardingsphere.datasource.master.username}
        password: ${spring.shardingsphere.datasource.master.password}
      slave2:
        type: ${spring.shardingsphere.datasource.master.type}
        driver-class-name: ${spring.shardingsphere.datasource.master.driver-class-name}
        url: jdbc:mysql://localhost:3306/mall_slave2?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false&&rewriteBatchedStatements=true
        username: ${spring.shardingsphere.datasource.master.username}
        password: ${spring.shardingsphere.datasource.master.password}
    masterslave:
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave1,slave2
    props:
      sql:
        show: true